# Spring Boot configuration
spring:
  flyway:
    out-of-order: true
  profiles:
    active: development
  mail:
    host: localhost
    username:
    password:
    port: 25


  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/avouch
    username: avouch
    password: avouch

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

# Logger configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

# Server configuration
server:
  port: 9000 #set your port

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
